# Generated by Django 5.1 on 2024-08-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do Produto')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo do Produto')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do Produto')),
                ('qtd', models.IntegerField(default=0, verbose_name='Quantidade do Produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
