# Generated by Django 5.1 on 2024-09-20 12:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_lucro_produto_margem_liquida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='lucro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Lucro por Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='margem_liquida',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Margem Líquida'),
        ),
    ]
